sudo: false
language: elixir
elixir:
  - "1.4"
  - "1.5"
  - "1.6"
  - "1.7"
  - "1.8"
otp_release:
  - 20.2
  - 21.0
addons:
  postgresql: "9.4"
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
script:
  - "mix format --check-formatted --dry-run"
  - "mix test"
