sudo: false
language: elixir
elixir:
  - 1.8.0
otp_release:
  - 21.2
matrix:
  include:
  - otp_release: 18.3
    elixir: 1.4.5
  - otp_release: 19.3
    elixir: 1.5.3
  - otp_release: 20.3
    elixir: 1.6.6
  - otp_release: 20.3
    elixir: 1.7.4
addons:
  postgresql: "9.3"
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
script:
  - "mix format --check-formatted --dry-run"
  - "mix test"
