os: linux
dist: xenial
language: elixir

jobs:
  include:
  - otp_release: 20.3
    elixir: 1.7.4
  - otp_release: 21.3
    elixir: 1.8.1
  - otp_release: 21.3
    elixir: 1.9.4
  - otp_release: 22.3
    elixir: 1.10.4
  - otp_release: 23.1
    elixir: 1.11.1

addons:
  postgresql: "9.4"
install:
  - mix local.rebar --force
  - mix local.hex --force
  - mix deps.get
script:
  - mix lint
  - mix test
after_script:
  - cd $TRAVIS_BUILD_DIR
  - MIX_ENV=docs mix inch.report
