name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MIX_ENV: test
  ELIXIR_ASSERT_TIMEOUT: 2000

jobs:
  test:
    name: test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.7
            otp: 21.3
          - elixir: 1.8
            otp: 21.3
          - elixir: 1.9
            otp: 21.3
          - elixir: 1.10
            otp: 22.3
          - elixir: 1.11
            otp: 22.3
          - elixir: 1.11
            otp: 23.1

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.elixir }}-${{ matrix.otp }}-mix-
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Install Dependencies
        run: mix do deps.get, deps.compile
      - name: Compile EctoVista
        run: mix compile --warnings-as-errors
      - name: Run Linter
        run: mix lint
      - name: Run Tests
        run: mix test